import {
  Prisma,
  ScholarshipRecordApplicationMode,
  ScholarshipRecordFundingType,
  ScholarshipRecordStatus,
} from '@prisma/client';
import type { PrismaService } from '../../../prisma/prisma.service';

type ScholarshipSeedItem = {
  code: string;
  title: string;
  description: string;
  provider: string;
  referenceCode: string | null;
  level: string | null;
  field: string | null;
  country: string | null;
  city: string | null;
  status: ScholarshipRecordStatus;
  fundingType: ScholarshipRecordFundingType | null;
  applicationMode: ScholarshipRecordApplicationMode;
  currency: string | null;
  amountLabel: string | null;
  amountMin: string | null;
  amountMax: string | null;
  coveragePercent: number | null;
  applicationFee: number | null;
  seats: number | null;
  isRenewable: boolean | null;
  renewableDurationMonths: number | null;
  interviewRequired: boolean | null;
  benefits: string[];
  conditions: string[];
  eligibilityCriteria: Prisma.InputJsonValue | null;
  requiredDocuments: Prisma.InputJsonValue | null;
  modalities: Prisma.InputJsonValue | null;
  selectionProcess: Prisma.InputJsonValue | null;
  contactInfo: Prisma.InputJsonValue | null;
  applicationUrl: string | null;
  applicationEmail: string | null;
  applicationPhone: string | null;
  applicationInstructions: string | null;
  startDate: Date | null;
  endDate: Date | null;
  applicationOpenAt: Date | null;
  applicationCloseAt: Date | null;
  resultDate: Date | null;
  isActive: boolean;
};

const scholarshipRecords: ScholarshipSeedItem[] = [
  {
    code: 'DBAU-RUS-2026-2027',
    title: 'Bourse russe 2026-2027',
    description:
      'Bourse de coopération Bénin–Russie pour études supérieures (bachelor, master, doctorat/spécialisation) avec dépôt de dossier à la DBAU.',
    provider: 'Gouvernement de la Fédération de Russie / DBAU Bénin',
    referenceCode: null,
    level: 'Licence, Master, Doctorat, Spécialisation',
    field: 'Filières prioritaires définies par communiqué DBAU',
    country: 'Russie',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: 'XOF',
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 5000,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse d’études supérieures en Russie'],
    conditions: [
      'Nationalité béninoise',
      'Ne pas être boursier en cours dans une université publique du Bénin',
    ],
    eligibilityCriteria: {
      ageByLevel: {
        bachelorMax: 25,
        masterMax: 35,
        doctorateMax: 40,
      },
      diplomaRules: 'Selon niveau demandé et équivalence reconnue',
    },
    requiredDocuments: {
      portalForm: 'education-in-russia.com',
      additionalDocuments: 'Voir communiqué officiel DBAU',
    },
    modalities: {
      hostCountry: 'Russie',
      localDeposit: 'DBAU Bénin',
      closingDateText: '16 janvier 2026 à 12h00',
    },
    selectionProcess: {
      stages: ['Soumission en ligne', 'Dépôt physique DBAU', 'Validation administrative'],
    },
    contactInfo: {
      source: 'DBAU',
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/bourse-russe-2026-2027/',
        'https://education-in-russia.com/',
      ],
    },
    applicationUrl: 'https://education-in-russia.com/',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Remplir le formulaire en ligne puis déposer le dossier à la DBAU.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: new Date('2026-01-16T12:00:00.000Z'),
    resultDate: null,

    isActive: true,
  },
  {
    code: 'DBAU-CHN-2026-2027',
    title: 'Bourse chinoise 2026-2027',
    description:
      'Bourse de coopération sino-béninoise avec candidatures pour licence, master, doctorat et spécialisation.',
    provider: 'Gouvernement chinois / DBAU Bénin',
    referenceCode: 'Agency Code 2041 (CSC)',
    level: 'Licence, Master, Doctorat, Spécialisation',
    field: 'Filières prioritaires publiées par cycle',
    country: 'Chine',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: null,
    seats: 4,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse d’études supérieures en Chine'],
    conditions: ['Nationalité béninoise', 'Conditions d’âge et diplôme selon niveau'],
    eligibilityCriteria: {
      ageByLevel: {
        licenceMax: 25,
        masterMax: 35,
        doctorateOrSpecializationMax: 40,
      },
      requiresCSCAForLicence: true,
    },
    requiredDocuments: {
      portal: 'http://www.campuschina.org',
      languageRequirement: 'Pièces uploadées en anglais ou chinois',
    },
    modalities: {
      programmeCategory: 'Type A',
      agencyCode: '2041',
      localDeposit: 'DBAU Bénin',
    },
    selectionProcess: {
      stages: ['Candidature Campuschina', 'Dépôt dossier DBAU', 'Examen des candidatures'],
    },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/bourse-chinoise-2026-2027/'],
    },
    applicationUrl: 'http://www.campuschina.org',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions:
      'Remplir la candidature CSC (Type A, code 2041) puis déposer à la DBAU.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: new Date('2026-01-07T12:30:00.000Z'),
    resultDate: null,

    isActive: true,
  },
  {
    code: 'DBAU-CUB-MED-2026-2027',
    title: 'Bourse Cuba (Médecine) 2026-2027',
    description:
      'Bourse médicale destinée aux jeunes béninois, avec quota très limité selon communiqué.',
    provider: 'Gouvernement de la République de Cuba / DBAU Bénin',
    referenceCode: 'Communiqué 0143 (référence document utilisateur)',
    level: 'Premier cycle',
    field: 'Médecine',
    country: 'Cuba',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.FULL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: null,
    seats: 1,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse d’études en médecine'],
    conditions: ['Baccalauréat 2024 ou 2025', 'Âge max 25 ans au 31/12/2026'],
    eligibilityCriteria: {
      socialCondition: 'Priorité aux candidats issus de familles à faible revenu',
    },
    requiredDocuments: {
      details: 'Voir communiqué DBAU associé',
    },
    modalities: {
      localDeposit: 'DBAU Bénin',
      deadlineFromDocument: '06 mars 2026',
    },
    selectionProcess: {
      stages: ['Dépôt dossier', 'Vérification éligibilité', 'Sélection finale'],
    },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/bourse-cubaine-2025-2026/'],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj/',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Consulter et suivre strictement le communiqué DBAU.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: new Date('2026-03-06T23:59:59.000Z'),
    resultDate: null,

    isActive: false,
  },
  {
    code: 'KNB-IDN-2026-2027',
    title: 'Bourse KNB Indonésie 2026-2027',
    description:
      'Programme Kemitraan Negara Berkembang (KNB) pour étudiants de pays en développement.',
    provider: 'Gouvernement indonésien (Kemdiktisaintek)',
    referenceCode: 'KNB 2026',
    level: 'Licence, Master, Doctorat',
    field: 'Toutes disciplines (selon universités partenaires)',
    country: 'Indonésie',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.FULL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: null,
    amountLabel: 'Bourse complète (selon modalités KNB)',
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Financement des études selon package KNB', 'Accès universités partenaires'],
    conditions: ['Être candidat international éligible selon règles KNB'],
    eligibilityCriteria: {
      details: 'Voir guide officiel KNB',
    },
    requiredDocuments: {
      details: 'Voir check-list portail KNB',
    },
    modalities: {
      selectionWindowText: '02 février 2026 au 31 mars 2026',
      announcementDateText: '19 juin 2026',
    },
    selectionProcess: {
      stages: ['Candidature en ligne', 'Évaluation', 'Publication des résultats'],
    },
    contactInfo: {
      sources: ['https://knb.kemdiktisaintek.go.id/'],
    },
    applicationUrl: 'https://knb.kemdiktisaintek.go.id/',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Suivre le portail officiel KNB et le guide annuel.',
    startDate: null,
    endDate: null,
    applicationOpenAt: new Date('2026-02-02T00:00:00.000Z'),
    applicationCloseAt: new Date('2026-03-31T23:59:59.000Z'),
    resultDate: new Date('2026-06-19T00:00:00.000Z'),

    isActive: true,
  },
  {
    code: 'DBAU-MAR-UNI-2025-2026',
    title: 'Bourse marocaine (formations universitaires)',
    description: 'Bourses de coopération Maroc–Bénin pour formations universitaires.',
    provider: 'Royaume du Maroc / DBAU Bénin',
    referenceCode: null,
    level: 'Cycles universitaires',
    field: 'Filières éligibles selon communiqué',
    country: 'Maroc',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: 'XOF',
    amountLabel: 'Complément mensuel requis côté famille',
    amountMin: '50000',
    amountMax: '50000',
    coveragePercent: null,
    applicationFee: null,
    seats: 80,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse d’études au Maroc'],
    conditions: ['Respect des critères DBAU et du partenaire marocain'],
    eligibilityCriteria: {
      details: 'Voir liste des filières et conditions par communiqué',
    },
    requiredDocuments: {
      details: 'Voir formulaire AMCI/DBAU',
    },
    modalities: {
      familyTopupXofPerMonth: 50000,
    },
    selectionProcess: {
      stages: ['Soumission dossier', 'Étude par DBAU/partie marocaine'],
    },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/bourse-marocaine-formations-universitaires-2025-2026/',
      ],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj/',
    applicationEmail: 'secretariat.dbau@gouv.bj',
    applicationPhone: null,
    applicationInstructions: 'Se référer au communiqué DBAU et au formulaire AMCI.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: true,
  },
  {
    code: 'IAEA-MSCFP-NUCLEAR',
    title: 'Programme AIEA Marie Sklodowska-Curie',
    description:
      "Programme de bourses pour étudiantes dans les domaines nucléaires (MSCFP de l'AIEA).",
    provider: 'AIEA (International Atomic Energy Agency)',
    referenceCode: 'MSCFP',
    level: 'Master principalement (selon appel MSCFP)',
    field: 'Sciences et technologies nucléaires',
    country: 'International',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.FULL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: null,
    amountLabel: 'Soutien financier + opportunités de stage selon programme',
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Soutien financier études', 'Possibilités de stage facilitées par le programme'],
    conditions: ['Candidature féminine dans le domaine nucléaire', 'Critères AIEA applicables'],
    eligibilityCriteria: {
      details: 'Voir conditions d’éligibilité MSCFP officielles',
    },
    requiredDocuments: {
      details: 'Voir formulaire et FAQ AIEA MSCFP',
    },
    modalities: {
      programmeType: 'Fellowship international',
    },
    selectionProcess: {
      stages: ['Candidature en ligne', 'Évaluation AIEA', 'Notification'],
    },
    contactInfo: {
      sources: [
        'https://www.iaea.org/services/key-programmes/iaea-marie-sklodowska-curie-fellowship-programme',
      ],
    },
    applicationUrl:
      'https://www.iaea.org/services/key-programmes/iaea-marie-sklodowska-curie-fellowship-programme',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Suivre les appels annuels publiés sur le site AIEA.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: true,
  },
  {
    code: 'DBAU-PAK-UMT-2026',
    title: 'Offre Pakistan - University of Management and Technology (Lahore)',
    description:
      'Offre de réduction des frais de scolarité pour candidatures béninoises (référence document utilisateur).',
    provider: 'University of Management and Technology Lahore / relais DBAU',
    referenceCode: null,
    level: 'Études supérieures',
    field: 'Selon filières UMT',
    country: 'Pakistan',
    city: 'Lahore',
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: 'Exonération 90% des frais de scolarité',
    amountMin: null,
    amountMax: null,
    coveragePercent: 90,
    applicationFee: null,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Réduction de 90% des frais de scolarité'],
    conditions: ['Voir annonce DBAU/Facebook DBAU et critères UMT'],
    eligibilityCriteria: {
      details: 'Critères académiques non centralisés dans une page DBAU indexée publiquement',
    },
    requiredDocuments: {
      details: 'À confirmer via annonce DBAU/Facebook DBAU',
    },
    modalities: {
      sourceType: 'Annonce DBAU/Facebook DBAU',
      deadlineTextFromDocument: '30 avril 2026',
    },
    selectionProcess: {
      stages: ['Soumission dossier', 'Évaluation partenaire'],
    },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/'],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj/',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Vérifier le communiqué concerné sur DBAU / Facebook DBAU.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: new Date('2026-04-30T23:59:59.000Z'),
    resultDate: null,

    isActive: true,
  },
  {
    code: 'DBAU-ROU-2026',
    title: 'Bourse Roumanie 2026',
    description:
      'Bourse de coopération pour études supérieures en Roumanie (référence document utilisateur).',
    provider: 'Partenariat Roumanie / relais DBAU',
    referenceCode: null,
    level: 'Études supérieures',
    field: 'Pluridisciplinaire (selon appel)',
    country: 'Roumanie',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: null,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Accès à des études supérieures en Roumanie'],
    conditions: ['Voir communiqué DBAU/Facebook DBAU'],
    eligibilityCriteria: {
      details: 'Portails généralement utilisés: studyinromania/scholarships.studyinromania',
    },
    requiredDocuments: {
      details: 'À confirmer sur communiqué local DBAU',
    },
    modalities: {
      sourceType: 'Annonce DBAU/Facebook DBAU',
      deadlineTextFromDocument: '31 mars 2026',
    },
    selectionProcess: {
      stages: ['Soumission', 'Étude dossier', 'Résultat'],
    },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/',
        'https://scholarships.studyinromania.gov.ro/',
      ],
    },
    applicationUrl: 'https://scholarships.studyinromania.gov.ro/',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Vérifier le communiqué DBAU exact de la campagne 2026.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: new Date('2026-03-31T23:59:59.000Z'),
    resultDate: null,

    isActive: true,
  },
  {
    code: 'DBAU-AZE-2025-2026',
    title: 'Bourse de l’Azerbaïdjan 2025-2026',
    description:
      'Bourse d’études supérieures pour licence, master, doctorat et spécialité médicale.',
    provider: 'République d’Azerbaïdjan / DBAU Bénin',
    referenceCode: null,
    level: 'Licence, Master, Doctorat, Spécialité médicale',
    field: 'Pluridisciplinaire selon appel',
    country: 'Azerbaïdjan',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.FULL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: 'Prise en charge complète selon communiqué',
    amountMin: null,
    amountMax: null,
    coveragePercent: 100,
    applicationFee: null,
    seats: 3,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: [
      'Frais de formation',
      'Billets aller-retour',
      'Allocations mensuelles',
      'Assurance maladie',
      'Frais de visa et inscription',
    ],
    conditions: ['Nationalité béninoise', 'Éligibilité académique selon niveau'],
    eligibilityCriteria: { details: 'Voir communiqué DBAU Azerbaïdjan' },
    requiredDocuments: { details: 'Formulaire spécifique + dossier complet' },
    modalities: { localDeposit: 'DBAU', deadlineText: '28 avril 2025' },
    selectionProcess: { stages: ['Soumission en ligne', 'Dépôt dossier', 'Sélection'] },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/bourse-de-lazerbaidjan-2025-2026/'],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj/',
    applicationEmail: 'dbau@gouv.bj',
    applicationPhone: null,
    applicationInstructions: 'Soumettre le dossier en ligne pour télécharger la fiche.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: new Date('2025-04-28T23:59:59.000Z'),
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-UNESCO-CHN-2024-2025',
    title: 'Bourse UNESCO/Chine 2024-2025 (Grande Muraille)',
    description:
      'Programme UNESCO/Chine ouvert aux États membres, incluant le Bénin, pour études supérieures.',
    provider: 'UNESCO / Gouvernement chinois / DBAU Bénin',
    referenceCode: 'Programme Grande Muraille',
    level: 'Études supérieures',
    field: 'Pluridisciplinaire',
    country: 'Chine',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.FULL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: null,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse de formation UNESCO/Chine'],
    conditions: ['Ne pas être boursier en cours dans les UPB', 'Respect des critères UNESCO/DBAU'],
    eligibilityCriteria: { details: 'Voir communiqué DBAU UNESCO/Chine' },
    requiredDocuments: { details: 'Dossier selon exigence du programme' },
    modalities: { localDeposit: 'DBAU' },
    selectionProcess: { stages: ['Soumission', 'Validation', 'Sélection finale'] },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/bourse-unesco-chine-2024-2025/'],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj/',
    applicationEmail: 'secretariat.dbau@gouv.bj',
    applicationPhone: null,
    applicationInstructions: 'Consulter le communiqué DBAU pour la procédure détaillée.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-ALG-UNI-2024-2025',
    title: 'Bourse algérienne (Formations universitaires) 2024-2025',
    description: 'Bourse de coopération pour poursuite d’études supérieures en Algérie.',
    provider: 'République Algérienne / DBAU Bénin',
    referenceCode: null,
    level: 'Formations universitaires',
    field: 'Pluridisciplinaire',
    country: 'Algérie',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.EMAIL,
    currency: 'XOF',
    amountLabel: 'Complément mensuel requis',
    amountMin: '50000',
    amountMax: '50000',
    coveragePercent: null,
    applicationFee: null,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse d’études supérieures en Algérie'],
    conditions: ['Complément mensuel familial de 50 000 FCFA'],
    eligibilityCriteria: { details: 'Critères académiques selon communiqué' },
    requiredDocuments: { details: 'Version numérique à envoyer à dbau@gouv.bj' },
    modalities: { transferProofRequired: true },
    selectionProcess: { stages: ['Envoi dossier', 'Étude administrative', 'Sélection'] },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/bourse-algerienneformations-universitaires-2024-2025/',
      ],
    },
    applicationUrl: null,
    applicationEmail: 'dbau@gouv.bj',
    applicationPhone: null,
    applicationInstructions: 'Transmettre la version numérique du dossier par email DBAU.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-TUN-2024-2025',
    title: 'Bourse tunisienne 2024-2025',
    description: 'Bourse de coopération pour études en Tunisie.',
    provider: 'République Tunisienne / DBAU Bénin',
    referenceCode: null,
    level: 'Études supérieures',
    field: 'Selon établissements tunisiens',
    country: 'Tunisie',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: 'XOF',
    amountLabel: 'Complément mensuel requis',
    amountMin: '50000',
    amountMax: '50000',
    coveragePercent: null,
    applicationFee: null,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Bourse d’études en Tunisie'],
    conditions: ['Engagement parent/candidat pour complément de 50 000 FCFA/mois'],
    eligibilityCriteria: { details: 'Voir communiqué DBAU Tunisie' },
    requiredDocuments: { details: 'Selon communiqué et check-list DBAU' },
    modalities: { transferProofEmail: 'secretariat.dbau@gouv.bj' },
    selectionProcess: { stages: ['Dossier', 'Instruction', 'Publication résultats'] },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/bourse-tunisienne-2024-2025/'],
    },
    applicationUrl: 'http://www.mes.tn/francais/index.htm',
    applicationEmail: 'secretariat.dbau@gouv.bj',
    applicationPhone: null,
    applicationInstructions: 'Voir offre DBAU et informations des établissements tunisiens.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-MAR-PRO-2025-2026',
    title: 'Bourse marocaine (Formations professionnelles) 2025-2026',
    description: 'Bourses OFPPT + places sans bourse dans le BTP.',
    provider: 'OFPPT Maroc / DBAU Bénin',
    referenceCode: null,
    level: 'Formation professionnelle',
    field: 'Métiers OFPPT / BTP',
    country: 'Maroc',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: 'XOF',
    amountLabel: 'Complément mensuel obligatoire',
    amountMin: '50000',
    amountMax: '50000',
    coveragePercent: null,
    applicationFee: null,
    seats: 20,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['20 bourses de formation professionnelle', '10 places sans bourse en BTP'],
    conditions: ['Complément familial de 50 000 FCFA/mois + preuve de transfert'],
    eligibilityCriteria: { details: 'Selon communiqué DBAU/OFPPT' },
    requiredDocuments: { details: 'Soumission en ligne des pièces + fiche inscription DBAU' },
    modalities: { transferProofEmail: 'dbau@gouv.bj' },
    selectionProcess: { stages: ['Candidature', 'Contrôle dossier', 'Sélection'] },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/bourse-marocaine-formations-professionnelles-2025-2026/',
      ],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj',
    applicationEmail: 'dbau@gouv.bj',
    applicationPhone: null,
    applicationInstructions: 'Soumettre en ligne les pièces pour télécharger la fiche.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-MAR-HORT-TS-2025-2026',
    title: 'Bourse marocaine technicien spécialisé en horticulture (BAC+2)',
    description: 'Bourse AMCI/CHA pour formation technicien spécialisé en horticulture.',
    provider: 'AMCI / CHA Agadir-Ait Melloul / DBAU Bénin',
    referenceCode: null,
    level: 'Technicien spécialisé (BAC+2)',
    field: 'Horticulture',
    country: 'Maroc',
    city: 'Agadir-Ait Melloul',
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: 'XOF',
    amountLabel: 'Complément mensuel obligatoire',
    amountMin: '50000',
    amountMax: '50000',
    coveragePercent: null,
    applicationFee: null,
    seats: 1,
    isRenewable: null,
    renewableDurationMonths: 24,
    interviewRequired: null,
    benefits: ['1 bourse d’étude en horticulture'],
    conditions: ['Complément mensuel 50 000 FCFA garanti avec les parents'],
    eligibilityCriteria: { details: 'Critères DBAU/AMCI' },
    requiredDocuments: { details: 'Soumission en ligne sur portail DBAU' },
    modalities: { transferCommitmentRequired: true },
    selectionProcess: { stages: ['Soumission', 'Instruction', 'Admission'] },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/bourse-marocaine-de-technicien-specialise-bac-02-ans-en-horticulture/',
      ],
    },
    applicationUrl: 'https://www.bourses.enseignementsuperieur.gouv.bj',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Soumettre les pièces en ligne puis dépôt selon consignes DBAU.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-MAR-HORT-MAS-2025-2026',
    title: 'Bourse marocaine Master en horticulture 2025-2026',
    description: 'Bourse AMCI/CHA pour master en aménagement paysager durable.',
    provider: 'AMCI / CHA Agadir-Ait Melloul / DBAU Bénin',
    referenceCode: null,
    level: 'Master',
    field: 'Aménagement paysager durable et réhabilitation',
    country: 'Maroc',
    city: 'Agadir-Ait Melloul',
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: 'XOF',
    amountLabel: 'Complément mensuel obligatoire',
    amountMin: '50000',
    amountMax: '50000',
    coveragePercent: null,
    applicationFee: null,
    seats: 1,
    isRenewable: null,
    renewableDurationMonths: 24,
    interviewRequired: null,
    benefits: ['1 bourse master en horticulture'],
    conditions: ['Engagement financier mensuel complémentaire 50 000 FCFA'],
    eligibilityCriteria: { details: 'Voir communiqué DBAU AMCI master horticulture' },
    requiredDocuments: { details: 'Dossier AMCI + pièces DBAU' },
    modalities: { transferProofRequired: true },
    selectionProcess: { stages: ['Candidature', 'Évaluation', 'Décision'] },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/bourse-marocaine-de-master-en-horticulture-2025-2026/',
      ],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Suivre le communiqué DBAU pour les étapes de soumission.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-WAPCO-CHN-BJ-2025',
    title: 'Bourses WAPCO (gaz et pétrole)',
    description:
      'Coopération Chine–Bénin: WAPCO offre des bourses aux étudiants béninois dans le domaine gaz/pétrole.',
    provider: 'WAPCO / partenaires Chine-Bénin / DBAU',
    referenceCode: null,
    level: 'Études supérieures',
    field: 'Gaz et pétrole',
    country: 'Chine',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.MIXED,
    currency: null,
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: null,
    seats: 10,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['10 bourses sectorielles gaz et pétrole'],
    conditions: ['Critères techniques selon appel WAPCO/DBAU'],
    eligibilityCriteria: { details: 'À consulter sur la publication DBAU concernée' },
    requiredDocuments: { details: 'Voir publication DBAU WAPCO' },
    modalities: { source: 'Opportunités de bourses DBAU' },
    selectionProcess: { stages: ['Candidature', 'Pré-sélection', 'Validation finale'] },
    contactInfo: {
      sources: ['https://bourses.enseignementsuperieur.gouv.bj/'],
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.gouv.bj/',
    applicationEmail: 'secretariat.dbau@gouv.bj',
    applicationPhone: '+2290120213988',
    applicationInstructions: 'Consulter l’article WAPCO sur DBAU pour les détails opérationnels.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: true,
  },
  {
    code: 'DBAU-MSCFP-2025',
    title: 'Bourse Marie Sklodowska-Curie (MSCFP) 2025',
    description:
      'Relais DBAU du programme IAEA MSCFP en faveur des femmes dans les domaines nucléaires.',
    provider: 'IAEA / DBAU Bénin',
    referenceCode: 'MSCFP 2025',
    level: 'Master (majoritairement)',
    field: 'Domaines nucléaires',
    country: 'International',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.FULL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: null,
    amountLabel: null,
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: null,
    renewableDurationMonths: null,
    interviewRequired: null,
    benefits: ['Soutien financier et accompagnement académique dans le nucléaire'],
    conditions: ['Candidatures féminines selon règles IAEA'],
    eligibilityCriteria: { details: 'Voir appel MSCFP 2025 DBAU/IAEA' },
    requiredDocuments: { details: 'Formulaire en ligne IAEA + pièces justificatives' },
    modalities: { source: 'Opportunités DBAU + portail IAEA' },
    selectionProcess: { stages: ['Application IAEA', 'Évaluation', 'Résultat'] },
    contactInfo: {
      sources: [
        'https://bourses.enseignementsuperieur.gouv.bj/',
        'https://www.iaea.org/services/key-programmes/iaea-marie-sklodowska-curie-fellowship-programme',
      ],
    },
    applicationUrl:
      'https://www.iaea.org/services/key-programmes/iaea-marie-sklodowska-curie-fellowship-programme',
    applicationEmail: 'mscfp@iaea.org',
    applicationPhone: null,
    applicationInstructions: 'Candidater sur le portail officiel IAEA MSCFP.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-BENIN-UPB-ALLOCATION-2025-2026',
    title: 'Allocations universitaires internes 2025-2026 (UPB)',
    description:
      "Campagne nationale DBAU de demandes d'allocations universitaires pour les universités publiques du Bénin.",
    provider: 'DBAU / MESRS Bénin',
    referenceCode: 'Campagne nationale allocations 2025-2026',
    level: 'Enseignement supérieur public',
    field: 'Toutes filières éligibles des universités publiques',
    country: 'Bénin',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: 'XOF',
    amountLabel: 'Allocation universitaire selon barème national',
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: true,
    renewableDurationMonths: 12,
    interviewRequired: false,
    benefits: ['Allocation universitaire annuelle', 'Prise en compte sociale et académique'],
    conditions: [
      'Être inscrit dans une université publique du Bénin',
      'Soumettre la demande sur la plateforme officielle',
      "Respecter les critères de la CNaBAU et de l'arrêté en vigueur",
    ],
    eligibilityCriteria: {
      scope: 'Universités publiques du Bénin',
      universities: ['UAC', 'UP', 'UNSTIM', 'UNA et autres UPB reconnues'],
      basis: 'Critères académiques, sociaux et administratifs',
      mandatoryPrerequisites: [
        'Certificat d’Identification Personnelle (CIP/ANIP)',
        'Préinscription universitaire validée',
        'Compte bancaire local + RIB 24 caractères',
      ],
    },
    requiredDocuments: {
      details: 'Pièces demandées par SYGAL/DBAU selon le profil candidat',
    },
    modalities: {
      portal: 'https://bourses.enseignementsuperieur.bj',
      campaignOpenDate: '2025-10-20',
      campaignCloseDate: '2026-02-08',
      selectionBody: 'CNaBAU',
      submissionType: '100% en ligne',
      applicantFlow: [
        'Inscrivez-vous',
        'Se connecter',
        'Demande en ligne',
        'Valider',
        'Renseigner contacts + infos bancaires',
        'Valider ma demande en ligne',
        'Payer les frais d’étude de la demande',
        'Payer pour valider votre demande',
        'Télécharger la fiche de demande',
      ],
      trackingFlow: ['Se connecter', 'Suivre sa demande en ligne'],
      trackingStatuses: ['En cours de traitement', 'Favorable', 'Réservé', 'Défavorable'],
      sourcePdf:
        'https://bourses.enseignementsuperieur.gouv.bj/wp-content/uploads/2025/10/1755-Demande-dallocation-UPB-2025-2026.pdf',
    },
    selectionProcess: {
      stages: [
        'Soumission en ligne (SYGAL)',
        'Vérification administrative',
        'Instruction/validation CNaBAU',
        'Publication des résultats',
      ],
    },
    contactInfo: {
      categoryPage:
        'https://bourses.enseignementsuperieur.gouv.bj/category/communiques-de-bourse-au-benin/',
      eService: 'https://bourses.enseignementsuperieur.gouv.bj/e-service/',
      email: 'secretariat.dbau@gouv.bj',
      phone: '(00229) 01 20 21 39 88',
      postal: '01 BP 348 Cotonou',
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.bj',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions:
      'Créer/ouvrir le compte candidat sur SYGAL puis compléter et soumettre le dossier en ligne.',
    startDate: null,
    endDate: null,
    applicationOpenAt: new Date('2025-10-20T00:00:00.000Z'),
    applicationCloseAt: new Date('2026-02-08T23:59:59.000Z'),
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-BENIN-UPB-ALLOCATION-2024-2025',
    title: 'Allocations universitaires internes 2024-2025 (UPB)',
    description:
      "Campagne nationale DBAU de demandes d'allocations universitaires pour les universités publiques du Bénin.",
    provider: 'DBAU / MESRS Bénin',
    referenceCode: 'Campagne nationale allocations 2024-2025',
    level: 'Enseignement supérieur public',
    field: 'Toutes filières éligibles des universités publiques',
    country: 'Bénin',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: 'XOF',
    amountLabel: 'Allocation universitaire selon barème national',
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: true,
    renewableDurationMonths: 12,
    interviewRequired: false,
    benefits: ['Allocation universitaire annuelle'],
    conditions: ['Être étudiant dans une UPB éligible', 'Respecter le calendrier officiel DBAU'],
    eligibilityCriteria: {
      scope: 'Universités publiques du Bénin',
      universities: ['UAC', 'UP', 'UNSTIM', 'UNA et autres UPB reconnues'],
      mandatoryPrerequisites: [
        'Inscription/Préinscription dans une UPB',
        'Soumission avant date limite',
      ],
    },
    requiredDocuments: {
      details: 'Documents exigés dans SYGAL au titre de 2024-2025',
    },
    modalities: {
      portal: 'https://bourses.enseignementsuperieur.bj',
      campaignOpenDate: '2024-10-21',
      campaignCloseDate: '2025-02-09',
      selectionBody: 'CNaBAU',
      submissionType: '100% en ligne',
      sourcePdf:
        'https://bourses.enseignementsuperieur.gouv.bj/wp-content/uploads/2024/10/communique-douverture-de-la-plateforme-2024-2025-.pdf',
    },
    selectionProcess: {
      stages: ['Demande en ligne', 'Contrôle dossier', 'Arbitrage CNaBAU', 'Publication'],
    },
    contactInfo: {
      announcement:
        'https://bourses.enseignementsuperieur.gouv.bj/ouverture-des-demandes-en-ligne-des-allocations-universitaires-au-titre-de-2024-2025/',
      email: 'secretariat.dbau@gouv.bj',
      phone: '(00229) 01 20 21 39 88',
      postal: '01 BP 348 Cotonou',
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.bj',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Dépôt exclusivement en ligne sur SYGAL.',
    startDate: null,
    endDate: null,
    applicationOpenAt: new Date('2024-10-21T00:00:00.000Z'),
    applicationCloseAt: new Date('2025-02-09T23:59:59.000Z'),
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-BENIN-UPB-ALLOCATION-2023-2024',
    title: 'Allocations universitaires internes 2023-2024 (UPB)',
    description:
      "Campagne nationale DBAU de demandes d'allocations universitaires pour les universités publiques du Bénin.",
    provider: 'DBAU / MESRS Bénin',
    referenceCode: 'Campagne nationale allocations 2023-2024',
    level: 'Enseignement supérieur public',
    field: 'Toutes filières éligibles des universités publiques',
    country: 'Bénin',
    city: null,
    status: ScholarshipRecordStatus.CLOSED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: 'XOF',
    amountLabel: 'Allocation universitaire selon barème national',
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: true,
    renewableDurationMonths: 12,
    interviewRequired: false,
    benefits: ['Allocation universitaire annuelle'],
    conditions: [
      'Être étudiant en université publique',
      'Respecter les conditions DBAU/CNaBAU de la campagne',
    ],
    eligibilityCriteria: {
      scope: 'UPB',
      universities: ['UAC', 'UP', 'UNSTIM', 'UNA et autres UPB reconnues'],
    },
    requiredDocuments: {
      details: 'Pièces exigées via la plateforme DBAU',
    },
    modalities: {
      portal: 'https://bourses.enseignementsuperieur.bj',
      campaignOpenDate: '2023-10-05',
      campaignCloseDate: '2024-02-04',
      selectionBody: 'CNaBAU',
      submissionType: '100% en ligne',
    },
    selectionProcess: {
      stages: ['Soumission', 'Vérification', 'Sélection CNaBAU', 'Résultats'],
    },
    contactInfo: {
      announcement: 'https://bourses.enseignementsuperieur.gouv.bj/847/',
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.bj',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Soumettre le dossier dans les délais de la campagne.',
    startDate: null,
    endDate: null,
    applicationOpenAt: new Date('2023-10-05T00:00:00.000Z'),
    applicationCloseAt: new Date('2024-02-04T23:59:59.000Z'),
    resultDate: null,

    isActive: false,
  },
  {
    code: 'DBAU-BENIN-UPB-ALLOCATION-GENERIC',
    title: 'Allocations universitaires internes (dispositif permanent UPB)',
    description:
      'Dispositif structurel de bourses/aides universitaires géré par la DBAU pour les universités publiques du Bénin, renouvelé chaque année via communiqué.',
    provider: 'DBAU / MESRS / CNaBAU',
    referenceCode: 'Dispositif national permanent',
    level: 'Enseignement supérieur public',
    field: 'Toutes filières éligibles',
    country: 'Bénin',
    city: null,
    status: ScholarshipRecordStatus.PUBLISHED,
    fundingType: ScholarshipRecordFundingType.PARTIAL,
    applicationMode: ScholarshipRecordApplicationMode.ONLINE,
    currency: 'XOF',
    amountLabel: 'Allocation variable selon barème et catégorie',
    amountMin: null,
    amountMax: null,
    coveragePercent: null,
    applicationFee: 0,
    seats: null,
    isRenewable: true,
    renewableDurationMonths: 12,
    interviewRequired: false,
    benefits: [
      'Bourses et aides universitaires nationales',
      'Accès via campagne annuelle officielle',
    ],
    conditions: [
      'Inscription dans une université publique béninoise',
      'Conformité aux critères réglementaires annuels',
    ],
    eligibilityCriteria: {
      targetInstitutions: ['UAC', 'UP', 'UNSTIM', 'UNA', 'autres UPB publiques'],
      governingBody: 'CNaBAU',
    },
    requiredDocuments: {
      details: 'Définis chaque année dans le communiqué d’ouverture',
    },
    modalities: {
      officialCategory:
        'https://bourses.enseignementsuperieur.gouv.bj/category/communiques-de-bourse-au-benin/',
      eService: 'https://bourses.enseignementsuperieur.gouv.bj/e-service/',
      portal: 'https://bourses.enseignementsuperieur.bj',
      selectionBody: 'CNaBAU',
      scope: 'Toutes universités publiques béninoises',
      annualCycle: 'Ouverture annuelle via communiqué DBAU',
    },
    selectionProcess: {
      stages: ['Appel à candidatures', 'Dépôt en ligne', 'Traitement CNaBAU', 'Publication'],
    },
    contactInfo: {
      institutional: 'https://bourses.enseignementsuperieur.gouv.bj/cnabau/',
    },
    applicationUrl: 'https://bourses.enseignementsuperieur.bj',
    applicationEmail: null,
    applicationPhone: null,
    applicationInstructions: 'Suivre le communiqué de campagne de l’année universitaire en cours.',
    startDate: null,
    endDate: null,
    applicationOpenAt: null,
    applicationCloseAt: null,
    resultDate: null,

    isActive: true,
  },
];

export async function seedScholarships(prisma: PrismaService) {
  for (const item of scholarshipRecords) {
    const data = {
      ...item,
      eligibilityCriteria:
        item.eligibilityCriteria === null ? Prisma.JsonNull : item.eligibilityCriteria,
      requiredDocuments: item.requiredDocuments === null ? Prisma.JsonNull : item.requiredDocuments,
      modalities: item.modalities === null ? Prisma.JsonNull : item.modalities,
      selectionProcess: item.selectionProcess === null ? Prisma.JsonNull : item.selectionProcess,
      contactInfo: item.contactInfo === null ? Prisma.JsonNull : item.contactInfo,
    };

    await prisma.scholarship.upsert({
      where: { code: item.code },
      update: {
        ...data,
      },
      create: {
        ...data,
      },
    });
    console.log(item.code);
  }
}
