export const FEATURE_CACHE_TTL_SECONDS = 300;
export const PROFILE_CACHE_TTL_SECONDS = 300;
export const RECOMMENDATION_CACHE_TTL_SECONDS = 300;

export const RESPONSE_VARIANCE_THRESHOLD = 4_000_000;
export const RESPONSE_SPEED_MAX_MS = 10_000;
export const HIGH_RESPONSE_TIME_MS = 8_000;
export const DEFAULT_RECOMMENDATION_LIMIT = 6;
export const RECOMMENDATION_MODEL_VERSION = 'v1';
